<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['ranger_db'] = array(
    'dsn' => '',
    'hostname' => '10.0.0.28',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['DWJ1'] = array(
    'dsn' => '',
    'hostname' => '10.0.24.4\\SQLDWJ1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_DWJ1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['DWJ2'] = array(
    'dsn' => '',
    'hostname' => '10.0.25.4\SQLDJJ1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_DWJ2',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['PSU1'] = array(
    'dsn' => '',
    'hostname' => '10.0.21.4\SQLPSU1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_PSU1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['KWI1'] = array(
    'dsn' => '',
    'hostname' => '10.0.17.4\SQLKWI1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_KWI1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['TSS1'] = array(
    'dsn' => '',
    'hostname' => '10.0.23.4\SQLTSS1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_TSS1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['KPR1'] = array(
    'dsn' => '',
    'hostname' => '10.0.32.4\SQLKPR1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_KPR1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);
$config['KMP1'] = array(
    'dsn' => '',
    'hostname' => '10.0.18.4\SQLKMP1',
    'username' => 'kmtr',
    'password' => 'sangtimur21',
    'database' => 'TIMBANGAN_KMP1',
    'dbdriver' => 'mssql',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);